#!/usr/bin/env bash

set -euxo pipefail

export BUILDKIT_PROGRESS=plain
export PROGRESS_NO_TRUNC=1

source ".env"

CROSS_TARGET="${CROSS_TARGET:-native}"

DOCKER_REPO="openblas_builder"
DOCKER_IMAGE_NAME_SAFE="${DOCKER_REPO//\//-}-${CROSS_TARGET}"
DOCKER_CONTAINER_NAME="${DOCKER_IMAGE_NAME_SAFE}-${CROSS_TARGET}-$(date -u "+%Y-%m-%d_%H-%M-%S_%3NZ")"

USER="user"
GROUP="user"

docker build \
  --file="./dev/${CROSS_TARGET}.dockerfile" \
  --tag="$DOCKER_IMAGE_NAME_SAFE" \
  --network=host \
  --build-arg="UID=$(id -u)" \
  --build-arg="GID=$(id -g)" \
  --build-arg="USER=${USER}" \
  --build-arg="GROUP=${GROUP}" \
  .

mkdir -p .build .cache/ccache .opt .out

docker run -it --rm \
  --init \
  --name="$DOCKER_CONTAINER_NAME" \
  --hostname="${DOCKER_IMAGE_NAME_SAFE}" \
  --user="$(id -u):$(id -g)" \
  --volume="$(pwd):/workdir" \
  --volume="$(pwd)/.opt:/opt/openblas" \
  --volume="$(pwd)/.cache/ccache:/cache/ccache" \
  --workdir="/workdir" \
  --env="CROSS_TARGET=${CROSS_TARGET}" \
  --env="UID=$(id -u)" \
  --env="GID=$(id -g)" \
  --env="USER=${USER}" \
  --env="GROUP=${GROUP}" \
  --env="PS1=\${USER}@\${HOST}" \
  --env="TZ=Etc/UTC" \
  --env="LANG=C.UTF-8" \
  --ulimit core=0 \
  "$DOCKER_IMAGE_NAME_SAFE" \
  bash ./scripts/main
