#!/usr/bin/env bash

set -euxo pipefail

: "${CROSS_TARGET:? "$0: \$CROSS_TARGET is not set"}"

export GIT_REPO_URL="https://github.com/OpenMathLib/OpenBLAS"
export VERSION="0.3.28"
export BRANCH="v${VERSION}"

export CFLAGS="-w ${CFLAGS:-}"
export CXXFLAGS="-w ${CXXFLAGS:-}"
export LDFLAGS="-s ${LDFLAGS:-}"

export CFLAGS="-static-libgcc -static-libstdc++ ${CFLAGS:-}"
export CXXFLAGS="-static-libgcc -static-libstdc++ ${CXXFLAGS:-}"
export LDFLAGS="-static-libgcc -static-libstdc++ ${LDFLAGS:-}"

#export CFLAGS="-static --static ${CFLAGS:-}"
#export CXXFLAGS="-static --static ${CXXFLAGS:-}"
#export LDFLAGS="-static --static ${LDFLAGS:-}"

export CFLAGS="-fPIC ${CFLAGS:-}"
export CXXFLAGS="-fPIC ${CXXFLAGS:-}"
export LDFLAGS="-fPIC ${LDFLAGS:-}"

#export CFLAGS="-pie -fPIE ${CFLAGS:-}"
#export CXXFLAGS="-pie -fPIE ${CXXFLAGS:-}"
#export LDFLAGS="-pie -fPIE ${LDFLAGS:-}"

#export CC="${CC:-gcc}"
#export CXX="${CXX:-g++}"
#export AR="${AR:-gcc-ar}"
#export NM="${NM:-gcc-nm}"
#export RANLIB="${RANLIB:-gcc-ranlib}"

export CCACHE_DIR="/cache/ccache"
export CCACHE_NOCOMPRESS="1"
export CCACHE_MAXSIZE="50G"
export CC="ccache ${CC:-gcc}"
export CXX="ccache ${CXX:-g++}"
export FC="${FC:-gfortran}"

export NAME="openblas"
export BUILD_DIR=".build"
export OUT_DIR=".out"
export INSTALL_DIR="/opt/${NAME}"

export NICE="nice -19 ionice -c2 -n5"
export JOBS="${JOBS:=$(($(nproc --all) + 2))}"

export build_time="$(date -u '+%Y-%m-%d_%H-%M-%S')"

function abspath() {
  readlink -m "$1"
}

function log() {
  tee -a "${1}" | stdbuf -oL grep --color=always -iE "error|fail|cannot|can't|unable|"
}

function package() {
  local input_dir="${1}"
  local output_tarball="${2}"

  ${NICE} find "${input_dir}" -printf "%P\n" \
    | ${NICE} tar --no-recursion -cf - -C "${input_dir}" --files-from=- \
    | ${NICE} xz -T0 -k > "${output_tarball}"
}


build_dir="$(abspath ${BUILD_DIR})/${CROSS_TARGET}"
outdir="$(abspath "${OUT_DIR}")"
mkdir -p "${build_dir}" "${outdir}"

pushd "$build_dir" >/dev/null
  src_dir="${NAME}-${VERSION}"

  if [ ! -d "${src_dir}" ]; then
    git clone --recursive --depth=1 -b "${BRANCH}" "${GIT_REPO_URL}" "${src_dir}"
  fi

  pushd "${src_dir}" >/dev/null
    export BINARY="${OPENBLAS_BINARY:-}"
    export TARGET="${OPENBLAS_TARGET:-}"
    export HOSTCC="${OPENBLAS_HOSTCC:-}"

    export CROSS="1"
    export DYNAMIC_ARCH="1"
    export FIXED_LIBNAME="1"

    export NO_SHARED=1
    export NO_STATIC=0

    ${NICE} make -j"${JOBS}" 2>&1 | log "build.log"

    ${NICE} make install PREFIX="${INSTALL_DIR}" 2>&1 | log "build.log"

    package "${INSTALL_DIR}" "${outdir}/${NAME}-${VERSION}-static-${CROSS_TARGET}-${build_time}.tar.xz"
  popd >/dev/null
popd >/dev/null


#      ${NICE} make -j"$(nproc)" 2>&1 | tee -a "build.log" | stdbuf -oL grep --color=always -iE "error|fail|fail|cannot|can't|unable|$"
#      ${NICE} make install 2>&1 | tee -a "build.log" | stdbuf -oL grep --color=always -iE "error|fail|fail|cannot|can't|unable|$"



#    cmake -LAH . 2>&1 || true | tee -a "build.log" | stdbuf -oL grep --color=always -iE "error|fail|fail|cannot|can't|unable|$"

#        -DCMAKE_C_COMPILER=gcc \
#        -DCMAKE_CXX_COMPILER=g++ \
#        -DCMAKE_Fortran_COMPILER=gfortran \
#        -DCMAKE_C_FLAGS="-w -fPIC --static -static -Bstatic ${CFLAGS:+:CFLAGS}" \
#        -DCMAKE_CXX_FLAGS="-w -fPIC --static -static -Bstatic ${CXXFLAGS:+:CXXFLAGS}" \
#        -DCMAKE_Fortran_FLAGS="-w -fPIC --static -static -Bstatic ${FCLAGS:+:FCLAGS}" \
#        -DCMAKE_EXE_LINKER_FLAGS="-w -static -static-libgcc ${LDFLAGS:+:LDFLAGS}" \

#          -DBINARY=64 \
#          -DBUILD_SHARED_LIBS=0 \
#          -DBUILD_TESTS=0 \
#          -DCONSISTENT_FPCSR=1 \
#          -DDYNAMIC_ARCH=1 \
#          -DINTERFACE64=1 \
#          -DNOFORTRAN=0 \
#          -DNO_AVX2=0 \
#          -DNO_AVX512=0 \
#          -DNO_AVX=0 \
#          -DNO_LAPACK=0 \
#          -DNUM_THREADS=8 \
#          -DUSE_LOCKING=0 \
#          -DUSE_OPENMP=0 \
#          -DUSE_THREAD=1 \
#        -DCROSS=1 \
#        -DNUM_PARALLEL="1" \
#        -DNUM_THREADS="8" \
